### ISSUE TITLE
Problemas al ejecutar el conector, con estos parámetros.

### ISSUE THREAD

**Issue by proyectovlci** [esri-es/Fiware-ArcGIS#2]
Versiones de SW utilizadas etc:
```
- OS: SUSE Linux Enterprise Server 11 SP3  (x86_64)
- Node.js (v.4.8.4)
- NPM: 2.15.11
- OpenSSL: 1-1.0.1g-0.28.2.x86_64
```

Adicionalmente, para evitar problemas con la comprobación de certificados etc, se han hecho estas configuraciónes de npm etc:

`smarmota#npm config set strict-ssl false`

En el código del programa "fiware_arcgis.js", antes de la linea 17 (`service.getToken(....)`) se ha añadido esta línea para evitar el testeo de certificados TLS:

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

Previo a la reconfiguración, todo parece estar OK a falta de la configuración del servidor arcgis:
 
```
smarmota# node fiware_arcgis.js
Response: {"code":400,"message":"Unable to generate token.","details":["'username' must be specified."]}
```

Procedo a configurar el acceso al servidor ArcGis con los siguientes parámetros:

```
    "debug": true,
    "port": 6443,
    "username":"proyectovlci",
    "password": "xxxxxx",
    "root_url": "sarcgis.aytoval.es",
    "services_url": "sarcgis.aytoval.es",
    "account_id": "",
```
   

(nótese “account_id” vacío, por indicación de técnicos de ESRI):

Intento ejecutar el conector  y el resultado es el siguiente (donde acabo simplemente perdido….) tiene pinta (por trazas que he hecho con “#strace –f” del proceso, de que si que se conecta al servidor etc… pero  que al no tener “account_id” no sabe formar el URL correctamente y lo que recibe es un error del servidor o una respuesta que el conector no sabe parsear)…  :
```
smarmota# node fiware_arcgis.js
undefined:1
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/x                                                                                        html1/DTD/xhtml1-strict.dtd">
^

SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/ddiaz/Fiware-ArcGIS/node_modules/arc-n                                                                                        ode/ArcNode.js:61:30)
    at emitOne (events.js:77:13)
    at IncomingMessage.emit (events.js:169:7)
    at IncomingMessage.Readable.read (_stream_readable.js:368:10)
    at flow (_stream_readable.js:759:26)
    at resume_ (_stream_readable.js:739:3)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)

```
 

Por dónde sigo??.

Un saludo. Gracias.

**Comment by proyectovlci** [comment]
Fichero <config.json> entero:

```
{
    "debug": false,
    "port": 6443,
    "username":"proyectovlci",
    "password": "xxxxxxxxxxx",
    "root_url": "sarcgis.aytoval.es",
    "services_url": "sarcgis.aytoval.es",
    "account_id": "",

    "sensors":{
        "EstacionClimaDatos":{
            "serviceName": "Datos Estaciones Clima de Valencia",
            "route": "/valencia_clima",
            "fields": [
                ["TimeInstant",     "esriFieldTypeDate"],
                ["IdDispositivo",   "esriFieldTypeInteger"],
                ["location",        "esriFieldTypeString"],
                ["VientoDireccion", "esriFieldTypeDouble"],
                ["VientoVelocidad", "esriFieldTypeDouble"],
                ["Temperatura",     "esriFieldTypeDouble"],
                ["HR",              "esriFieldTypeDouble"],
                ["PresionBar",      "esriFieldTypeDouble"],
                ["Precipitaciones", "esriFieldTypeDouble"]
            ]
        },

        "EstacionAireDatos":{
             "serviceName": "Datos Estaciones Aire de Valencia",
             "route": "/valencia_calidadaire",
             "fields": [
                ["TimeInstant",  "esriFieldTypeDate"],
                ["IdEstacion",   "esriFieldTypeInteger"],
                ["location",     "esriFieldTypeString"],
                ["medida-SO2",   "esriFieldTypeDouble"],
                ["medida-NO2",   "esriFieldTypeDouble"],
                ["medida-O3",    "esriFieldTypeDouble"],
                ["medida-CO",    "esriFieldTypeDouble"],
                ["medida-PM10",  "esriFieldTypeDouble"],
                ["medida-PM25",  "esriFieldTypeDouble"]
             ]

        }
    }
}


```

**Comment by hhkaos** [comment]
Gracias @proyectovlci , voy a intentar reproducir el error con [node-debug](https://www.npmjs.com/package/node-debug), pero tiene pinta de que está recibiendo un HTML donde espera un JSON y falla al parsear.
