### ISSUE TITLE
Error al utilizar el conector

### ISSUE THREAD

**Issue by esrisoportesp** [esri-es/Fiware-ArcGIS#4]
Estamos intentando publicar datos en nuestra Organización. El feature se crea en la cuenta de la Organización pero no se consigue cargar la información desde FIWARE.
El error que se genera es el siguiente al hacer el POST:

```
Error chunk
SyntaxError: Unexpected token < in JSON at position 0
ArcNode.js:241
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/home/jandres/repositorios/Miraflores/Fiware-ArcGIS/node_modules/arc-node/ArcNode.js:241:30)
    at emitOne (events.js:116:13)
    at IncomingMessage.emit (events.js:211:7)
    at IncomingMessage.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

El fichero config.json utilizado tiene este contenido:

```js
{
    "debug": true,
    "port": 4003,
    "username": "xxxxxxxx",
    "password": "xxxxxxxx",
    "root_url": "xxxxx.maps.arcgis.com",
    "services_url": "xxxxx.maps.arcgis.com",
    "account_id": "XXXXXXXXXX",

    "sensors":{

        "EDAR" : {
            "serviceName": "FWPruebaUM5a",
            "route": "/FWUMPrueba5a",
            "fields": [
                ["B_BS_RADIACION", "esriFieldTypeDouble"],
                ["B_BS_VEL", "esriFieldTypeDouble"],
                ["id", "esriFieldTypeString"],
                ["B_CAMPO_ANGULO_SISTEMA", "esriFieldTypeDouble"],
                ["B_CAMPO_VELOCIDAD_VIENTO", "esriFieldTypeDouble"],
                ["B_FT01", "esriFieldTypeDouble"],
                ["B_FT02", "esriFieldTypeDouble"],
                ["B_PT01", "esriFieldTypeDouble"],
                ["B_PT02", "esriFieldTypeDouble"]
            ]
        }

    }
 }
 ```
 
Muchas gracias

**Comment by ntkog** [comment]
Hola!

El error 
```bash
SyntaxError: Unexpected token < in JSON at position 0
```
Tiene pinta de que el endpoint al que estáis intentando hacer un post , devuelve un HTML , no un JSON. 

Revisad que efectivamente estáis haciendo el post correctamente ,

Saludos!

**Comment by hhkaos** [comment]
Efectivamente, el problema pone que está dando en la línea 241 de [ArcNode](https://github.com/esri-es/ArcNode/blob/master/ArcNode.js), aunque no sé qué versión usáis, yo diría que es [en esta línea](https://github.com/esri-es/ArcNode/blob/master/ArcNode.js#L284) donde casca. 

Si podéis [debuggear](https://nodejs.org/en/docs/guides/debugging-getting-started/) el código y ver qué está enviando en el POST se verá mejor.
